---
title: "nyctech_dataviz"
author: "Jenn Schilling"
date: "6/10/2020"
output: html_document
---

**Things to visualize:**  
* Overall average for every category  
* Average size of female founded companies in the set  	
* Average #s across all depts for all female founded companies  
* Average size of male founded companies in the set  
* Average #s acorss all depts for all male founded companies

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
library(tidyr)
library(dplyr)
library(ggplot2)
library(ggtext)
library(cowplot)

data <- read_xlsx("Gender Diversity in NY Numbers.xlsx", sheet = "Sheet1")

```

```{r data processing}

# Make data long and calculate % Female and Male of each company and department
# Check that the total equals the sum of female and male
data.long <- data %>%
  pivot_longer(Headcount_Total:Other_F, names_to = "colnames") %>%
  separate(colnames, into = c("Department", "Label"), sep = "_") %>%
  pivot_wider(names_from = Label, values_from = value) %>%
  mutate(Department = ifelse(Department == "Headcount", "Company", 
                             ifelse(Department == "Eng", "Engineering",
                                    ifelse(Department == "Mkt", "Marketing", Department)))) %>%
  mutate(headcount_check = (M + F) == Total,
         M_Percent = M / Total,
         F_Percent = F / Total)

nonmatch <- data.long %>% filter(headcount_check == FALSE)

# write.csv(nonmatch, "headcountsum_nonmatch.csv", row.names = FALSE)

# Create average percent female and average sizes over deparments by founded
data.avg <- data.long %>%
  filter(Total != 0) %>% # Remove departments with no people in them
  group_by(Founded, Department) %>%
  summarise(avg.size = mean(Total),
            avg.percent.F = mean(F_Percent)) %>%
  ungroup() %>%
  mutate(Founded = ifelse(Founded == "M", "Male", "Female"))


```

```{r visualization}

# Company Total with Percent Labels
ggplot(data = data.avg %>% filter(Department == "Company")) +
  geom_bar(mapping = aes(x = Founded, y = avg.size, fill = Founded), stat = "Identity") +
  geom_text(aes(x = Founded, y = avg.size, label = paste0(scales::percent(avg.percent.F, accuracy = 1), " Female Employees")), 
            position = position_dodge(width = .9),    # move to center of bars
            vjust = -0.5) +    # nudge above top of bar  
  scale_fill_brewer(palette = "Set2") +
  xlab("Gender of Founder") +
  ylab("Average Total Number of \n New York Based Employees") +
  labs(title = "New York Based Tech Companies with <b style='color:#66c2a5'>female</b> founders on average have <b>fewer total employees</b> <br> than those with <b style='color:#fc8d62'>male</b> founders, but <b style='color:#66c2a5'>female</b> founded companies on average have a <b>greater<br> proportion of female employees</b>.") +
  theme_classic(base_size = 14) +
  theme(legend.position = "none",
        plot.title = element_markdown(lineheight = 1.1)) 

# Company Total and Percent
company.total <- ggplot(data = data.avg %>% filter(Department == "Company")) +
  geom_bar(mapping = aes(x = Founded, y = avg.size, fill = Founded), stat = "Identity") +
    geom_text(aes(x = Founded, y = avg.size, label = round(avg.size, 0)), 
            position = position_dodge(width = .9),    # move to center of bars
            vjust = -0.5) +    # nudge above top of bar 
  scale_fill_brewer(palette = "Set2") +
  xlab("Gender of Founder") +
  ylab("Average Total Number of \n New York Based Employees") +
  theme_classic(base_size = 14) +
  theme(legend.position = "none") 

company.percent <- ggplot(data = data.avg %>% filter(Department == "Company")) +
  geom_bar(mapping = aes(x = Founded, y = avg.percent.F, fill = Founded), stat = "Identity") +
    geom_text(aes(x = Founded, y = avg.percent.F, label = scales::percent(avg.percent.F, accuracy = 1)), 
            position = position_dodge(width = .9),    # move to center of bars
            vjust = -0.5) +    # nudge above top of bar 
  scale_fill_brewer(palette = "Set2") +
  xlab("Gender of Founder") +
  ylab("Average Percent of New York Based \nEmployees Identifying as Female") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), limits = c(0, 1)) +
  theme_classic(base_size = 14) +
  theme(legend.position = "none") 

# Lines Below: https://wilkelab.org/cowplot/articles/plot_grid.html

plot_row <- plot_grid(company.total, company.percent)

# now add the title
title <- ggplot() + 
  labs(title = "New York Based Tech Companies with <b style='color:#66c2a5'>female</b> founders on average have <b>fewer total employees</b> <br> than those with <b style='color:#fc8d62'>male</b> founders, but <b style='color:#66c2a5'>female</b> founded companies on average have a <b>greater<br> proportion of female employees</b>.") +
  theme_classic(base_size = 14) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 20),
    plot.title = element_markdown(lineheight = 1.1),
    line = element_blank()
  )

plot_grid(
  title, plot_row,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.15, 1)
)

# Department Percentages
ggplot(data = data.avg %>% filter(Department != "Company"),
       aes(x = Founded, y = avg.percent.F, fill = Founded, label = scales::percent(avg.percent.F, accuracy = 1))) +
  geom_col(position = 'dodge') + 
 # geom_text(position = position_dodge(width = .9),    # move to center of bars
 #            vjust = -0.5) +    # nudge above top of bar  
  facet_wrap(~ Department) +
  scale_fill_brewer(palette = "Set2") +
  xlab("Gender of Founder") +
  ylab("Average Percent of New York Based \nEmployees Identifying as Female") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), limits = c(0, 1)) +
  labs(title = "New York Based Tech Companies with <b style='color:#66c2a5'>female</b> founders on average have a <b>higher proportion of female</b><br> employees in each department than those with <b style='color:#fc8d62'>male</b> founders.") +
  theme_classic(base_size = 14) +
  theme(legend.position = "none",
        plot.title = element_markdown(lineheight = 1.1)) 


```

